export const SELECT_BASE_CURRENCY = 'SELECT_BASE_CURRENCY';
export const SELECT_TO_CURRENCY = 'SELECT_TO_CURRENCY';

export const SELECT_BASE_SYMBOL = 'SELECT_BASE_SYMBOL';
export const SELECT_TO_SYMBOL = 'SELECT_TO_SYMBOL';

export const DISABLE_EXCHANGE_BTN = 'DISABLE_EXCHANGE_BTN';
export const ENABLE_EXCHANGE_BTN = 'ENABLE_EXCHANGE_BTN';

export const RATES_FETCH = 'RATES_FETCH';
export const RATES_ADD = 'RATES_ADD';
