export const SELECT_BASE_CURRENCY = 'SELECT_BASE_CURRENCY';
export const SELECT_TO_CURRENCY = 'SELECT_TO_CURRENCY';

export const SELECT_BASE_SYMBOL = 'SELECT_BASE_SYMBOL';
export const SELECT_TO_SYMBOL = 'SELECT_TO_SYMBOL';

export const DISABLE_EXCHANGE_BTN = 'DISABLE_EXCHANGE_BTN';
export const ENABLE_EXCHANGE_BTN = 'ENABLE_EXCHANGE_BTN';

export const EXCHANGE = 'EXCHANGE';
export const EXCHANGE_BALANCE = 'EXCHANGE_BALANCE';

export const RATES_FETCH = 'RATES_FETCH';
export const RATES_FETCH_ERROR = 'RATES_FETCH_ERROR';

export const RATES_ADD = 'RATES_ADD';

export const INPUT_FROM = 'INPUT_FROM';
export const INPUT_TO = 'INPUT_TO';
export const DISPLAY_INPUT_FROM = 'CHANGE_INPUT_FROM';
export const DISPLAY_INPUT_TO = 'CHANGE_INPUT_TO';
export const RESET_INPUTS = 'RESET_INPUTS';
